default&post:
  INPUTS: 
  OUTPUTS:
    output_folder#outputfolder:
  SKIPPABLE: True
  __VALIDATE_STAGE:
    "*object": stagecoach.validation.StageValidator
    outputs: ${OUTPUTS}
    skippable: ${SKIPPABLE}