default&post:
  __ID#uuid4:
  __SYSTEM#systeminfo:
  __DATETIME#datetimenow:
  INPUTS: 
  OUTPUTS:
    output_folder#outputfolder:
  SKIPPABLE: True
  _VALIDATE_STAGE:
    "*object": stagecoach.validation.StageValidator
    outputs: ${OUTPUTS}
    skippable: ${SKIPPABLE}