stagecoach:
  default:
    SKIPPABLE: False
    learning_rate: 1.0

    output_folder: ${OUTPUTS:output_folder.path}/stage_output

    stages!required:
    trails!required:

    stage_coach#trails:
      output_folder: ${OUTPUTS:output_folder.path}
      stages: ${stages}
      trails: ${trails}

    run:
      "*object": stagecoach.run
      stage_coach: ${stage_coach}