stagecoach:
  default:
    SKIPPABLE: False
    learning_rate: 1.0
    output_folder: ${OUTPUTS:output_folder.path}

    stages!required:
    trails!required:

    stage_coach#stagecoach:
      output_folder: ${OUTPUTS:output_folder.path}
      stages: ${stages}
      trails: ${trails}